ActiveSkill.create!([
  {name: "Negate Poison", skill_id: 84, points: 10, display_alias: nil},
  {name: "Double Poison", skill_id: 84, points: -10, display_alias: nil},
  {name: "Negate Paralysis", skill_id: 77, points: 10, display_alias: nil},
  {name: "Double Paralysis", skill_id: 77, points: -10, display_alias: nil},
  {name: "Negate Sleep", skill_id: 108, points: 10, display_alias: nil},
  {name: "Double Sleep", skill_id: 108, points: -10, display_alias: nil},
  {name: "Halve Stun", skill_id: 40, points: 10, display_alias: nil},
  {name: "Negate Stun", skill_id: 40, points: 15, display_alias: nil},
  {name: "Double Stun", skill_id: 40, points: -10, display_alias: nil},
  {name: "Negate Mud/Snow", skill_id: 113, points: 10, display_alias: nil},
  {name: "Iron Skin", skill_id: 27, points: 10, display_alias: nil},
  {name: "Bio Student", skill_id: 8, points: 10, display_alias: nil},
  {name: "Bio Master", skill_id: 8, points: 15, display_alias: nil},
  {name: "Attack Up (S)", skill_id: 6, points: 10, display_alias: nil},
  {name: "Attack Up (M)", skill_id: 6, points: 15, display_alias: nil},
  {name: "Attack Up (L)", skill_id: 6, points: 20, display_alias: nil},
  {name: "Attack Up (U)", skill_id: 6, points: 25, display_alias: nil},
  {name: "Attack Down (S)", skill_id: 6, points: -10, display_alias: nil},
  {name: "Attack Down (M)", skill_id: 6, points: -15, display_alias: nil},
  {name: "Attack Down (L)", skill_id: 6, points: -20, display_alias: nil},
  {name: "Defense Up (S)", skill_id: 26, points: 10, display_alias: nil},
  {name: "Defense Up (M)", skill_id: 26, points: 15, display_alias: nil},
  {name: "Defense Up (L)", skill_id: 26, points: 20, display_alias: nil},
  {name: "Defense Up (U)", skill_id: 26, points: 25, display_alias: nil},
  {name: "Defense Down (S)", skill_id: 26, points: -10, display_alias: nil},
  {name: "Defense Down (M)", skill_id: 26, points: -15, display_alias: nil},
  {name: "Defense Down (L)", skill_id: 26, points: -20, display_alias: nil},
  {name: "Health +20", skill_id: 60, points: 10, display_alias: nil},
  {name: "Health +50", skill_id: 60, points: 15, display_alias: nil},
  {name: "Health -10", skill_id: 60, points: -10, display_alias: nil},
  {name: "Health -30", skill_id: 60, points: -15, display_alias: nil},
  {name: "Rec Speed +1", skill_id: 97, points: 10, display_alias: nil},
  {name: "Rec Speed +2", skill_id: 97, points: 15, display_alias: nil},
  {name: "Rec Speed -1", skill_id: 97, points: -10, display_alias: nil},
  {name: "Rec Speed -2", skill_id: 97, points: -15, display_alias: nil},
  {name: "Divine Protection", skill_id: 91, points: 10, display_alias: nil},
  {name: "Demonic Protection", skill_id: 91, points: -10, display_alias: nil},
  {name: "Quick Sheath", skill_id: 105, points: 10, display_alias: nil},
  {name: "Focus", skill_id: 41, points: 10, display_alias: nil},
  {name: "Distraction", skill_id: 41, points: -10, display_alias: nil},
  {name: "Critical Eye +1", skill_id: 39, points: 10, display_alias: nil},
  {name: "Critical Eye +2", skill_id: 39, points: 15, display_alias: nil},
  {name: "Critical Eye +3", skill_id: 39, points: 20, display_alias: nil},
  {name: "Critical Master", skill_id: 39, points: 30, display_alias: nil},
  {name: "Critical Eye -1", skill_id: 39, points: -10, display_alias: nil},
  {name: "Critical Eye -2", skill_id: 39, points: -15, display_alias: nil},
  {name: "Critical Eye -3", skill_id: 39, points: -20, display_alias: nil},
  {name: "Weakness Exploit", skill_id: 129, points: 10, display_alias: nil},
  {name: "Part Breaker", skill_id: 28, points: 10, display_alias: nil},
  {name: "Knockout King", skill_id: 69, points: 10, display_alias: nil},
  {name: "Stamina Thief", skill_id: 118, points: 10, display_alias: nil},
  {name: "Constitution +1", skill_id: 23, points: 10, display_alias: nil},
  {name: "Constitution +2", skill_id: 23, points: 15, display_alias: nil},
  {name: "Constitution -1", skill_id: 23, points: -10, display_alias: nil},
  {name: "Constitution -2", skill_id: 23, points: -15, display_alias: nil},
  {name: "Earplugs", skill_id: 61, points: 10, display_alias: nil},
  {name: "HG Earplugs", skill_id: 61, points: 15, display_alias: nil},
  {name: "Windproof (Lo)", skill_id: 144, points: 10, display_alias: nil},
  {name: "Windproof (Hi)", skill_id: 144, points: 15, display_alias: nil},
  {name: "Tremor Resistence", skill_id: 136, points: 10, display_alias: nil},
  {name: "Heat Cancel", skill_id: 62, points: 10, display_alias: nil},
  {name: "Heat Surge", skill_id: 62, points: -10, display_alias: nil},
  {name: "Cold Cancel", skill_id: 19, points: 10, display_alias: nil},
  {name: "Cold Surge", skill_id: 19, points: -10, display_alias: nil},
  {name: "Marathon Runner", skill_id: 117, points: 10, display_alias: nil},
  {name: "Short Sprinter", skill_id: 117, points: -10, display_alias: nil},
  {name: "Stamina Recovery Up", skill_id: 119, points: 10, display_alias: nil},
  {name: "Stamina Recovery Down", skill_id: 119, points: -10, display_alias: nil},
  {name: "Evasion +1", skill_id: 37, points: 10, display_alias: nil},
  {name: "Evasion +2", skill_id: 37, points: 15, display_alias: nil},
  {name: "Evasion +3", skill_id: 37, points: 20, display_alias: nil},
  {name: "Evasion Down", skill_id: 37, points: -10, display_alias: nil},
  {name: "Evade Extender", skill_id: 36, points: 10, display_alias: nil},
  {name: "Sneak", skill_id: 102, points: 10, display_alias: nil},
  {name: "Taunt", skill_id: 102, points: -10, display_alias: nil},
  {name: "Guard +1", skill_id: 55, points: 10, display_alias: nil},
  {name: "Guard +2", skill_id: 55, points: 15, display_alias: nil},
  {name: "Guard -1", skill_id: 55, points: -10, display_alias: nil},
  {name: "Guard Boost", skill_id: 56, points: 10, display_alias: nil},
  {name: "Status Attack +1", skill_id: 120, points: 10, display_alias: nil},
  {name: "Status Attack +2", skill_id: 120, points: 15, display_alias: nil},
  {name: "Status Attack Down", skill_id: 120, points: -10, display_alias: nil},
  {name: "Elemental Attack Up", skill_id: 34, points: 10, display_alias: nil},
  {name: "Elemental Attack Down", skill_id: 34, points: -10, display_alias: nil},
  {name: "Fire Attack +1", skill_id: 45, points: 10, display_alias: nil},
  {name: "Fire Attack +2", skill_id: 45, points: 15, display_alias: nil},
  {name: "Fire Attack +3", skill_id: 45, points: 20, display_alias: nil},
  {name: "Fire Attack Down", skill_id: 45, points: -10, display_alias: nil},
  {name: "Water Attack +1", skill_id: 140, points: 10, display_alias: nil},
  {name: "Water Attack +2", skill_id: 140, points: 15, display_alias: nil},
  {name: "Water Attack +3", skill_id: 140, points: 20, display_alias: nil},
  {name: "Water Attack Down", skill_id: 140, points: -10, display_alias: nil},
  {name: "Thunder Attack +1", skill_id: 130, points: 10, display_alias: nil},
  {name: "Thunder Attack +2", skill_id: 130, points: 15, display_alias: nil},
  {name: "Thunder Attack +3", skill_id: 130, points: 20, display_alias: nil},
  {name: "Thunder Attack Down", skill_id: 130, points: -10, display_alias: nil},
  {name: "Ice Attack +1", skill_id: 66, points: 10, display_alias: nil},
  {name: "Ice Attack +2", skill_id: 66, points: 15, display_alias: nil},
  {name: "Ice Attack +3", skill_id: 66, points: 20, display_alias: nil},
  {name: "Ice Attack Down", skill_id: 66, points: -10, display_alias: nil},
  {name: "Dragon Attack +1", skill_id: 30, points: 10, display_alias: nil},
  {name: "Dragon Attack +2", skill_id: 30, points: 15, display_alias: nil},
  {name: "Dragon Attack +3", skill_id: 30, points: 20, display_alias: nil},
  {name: "Dragon Attack Down", skill_id: 30, points: -10, display_alias: nil},
  {name: "Fire Res (S)", skill_id: 46, points: 10, display_alias: nil},
  {name: "Fire Res (L)", skill_id: 46, points: 15, display_alias: nil},
  {name: "Fire Res Down", skill_id: 46, points: -10, display_alias: nil},
  {name: "Water Res (S)", skill_id: 141, points: 10, display_alias: nil},
  {name: "Water Res (L)", skill_id: 141, points: 15, display_alias: nil},
  {name: "Water Res Down", skill_id: 141, points: -10, display_alias: nil},
  {name: "Thunder Res (S)", skill_id: 131, points: 10, display_alias: nil},
  {name: "Thunder Res (L)", skill_id: 131, points: 15, display_alias: nil},
  {name: "Thunder Res Down", skill_id: 131, points: -10, display_alias: nil},
  {name: "Ice Res (S)", skill_id: 67, points: 10, display_alias: nil},
  {name: "Ice Res (L)", skill_id: 67, points: 15, display_alias: nil},
  {name: "Ice Res Down", skill_id: 67, points: -10, display_alias: nil},
  {name: "Dragon Res (S)", skill_id: 31, points: 10, display_alias: nil},
  {name: "Dragon Res (L)", skill_id: 31, points: 15, display_alias: nil},
  {name: "Dragon Res Down", skill_id: 31, points: -10, display_alias: nil},
  {name: "Razor Sharp", skill_id: 104, points: 10, display_alias: nil},
  {name: "Blunt Edge", skill_id: 104, points: -10, display_alias: nil},
  {name: "Sharpness +1", skill_id: 58, points: 10, display_alias: nil},
  {name: "Speed Sharpening", skill_id: 103, points: 10, display_alias: nil},
  {name: "Slow Sharpening", skill_id: 103, points: -10, display_alias: nil},
  {name: "Punishing Draw", skill_id: 93, points: 10, display_alias: nil},
  {name: "Critical Draw", skill_id: 25, points: 10, display_alias: nil},
  {name: "Mind's Eye", skill_id: 43, points: 10, display_alias: nil},
  {name: "Reload Speed +1", skill_id: 100, points: 10, display_alias: nil},
  {name: "Reload Speed +2", skill_id: 100, points: 15, display_alias: nil},
  {name: "Reload Speed +3", skill_id: 100, points: 20, display_alias: nil},
  {name: "Reload Speed -1", skill_id: 100, points: -10, display_alias: nil},
  {name: "Reload Speed -2", skill_id: 100, points: -15, display_alias: nil},
  {name: "Reload Speed -3", skill_id: 100, points: -20, display_alias: nil},
  {name: "Load Up", skill_id: 71, points: 10, display_alias: nil},
  {name: "Bonus Shot", skill_id: 96, points: 10, display_alias: nil},
  {name: "Recoil Reduction +1", skill_id: 98, points: 10, display_alias: nil},
  {name: "Recoil Reduction +2", skill_id: 98, points: 15, display_alias: nil},
  {name: "Recoil Reduction +3", skill_id: 98, points: 20, display_alias: nil},
  {name: "Recoil Reduction -1", skill_id: 98, points: -10, display_alias: nil},
  {name: "Recoil Reduction -2", skill_id: 98, points: -15, display_alias: nil},
  {name: "Recoil Reduction -3", skill_id: 98, points: -20, display_alias: nil},
  {name: "Steadiness +1", skill_id: 90, points: 10, display_alias: nil},
  {name: "Steadiness +2", skill_id: 90, points: 15, display_alias: nil},
  {name: "Steadiness -1", skill_id: 90, points: -10, display_alias: nil},
  {name: "Steadiness -2", skill_id: 90, points: -15, display_alias: nil},
  {name: "Normal/Rapid Up", skill_id: 76, points: 10, display_alias: nil},
  {name: "Pierce/Pierce Up", skill_id: 83, points: 10, display_alias: nil},
  {name: "Pellet/Scatter Up", skill_id: 80, points: 10, display_alias: nil},
  {name: "NormalS All Add", skill_id: 75, points: 10, display_alias: nil},
  {name: "PierceS Lv1 Add", skill_id: 82, points: 10, display_alias: nil},
  {name: "PierceS All Add", skill_id: 82, points: 15, display_alias: nil},
  {name: "PelletS Lv1 Add", skill_id: 79, points: 10, display_alias: nil},
  {name: "PelletS All Add", skill_id: 79, points: 15, display_alias: nil},
  {name: "CragS Lv1 Add", skill_id: 24, points: 10, display_alias: nil},
  {name: "CragS All Add", skill_id: 24, points: 15, display_alias: nil},
  {name: "ClustS Lv1 Add", skill_id: 18, points: 10, display_alias: nil},
  {name: "ClustS All Add", skill_id: 18, points: 15, display_alias: nil},
  {name: "SlicingS Add", skill_id: 110, points: 10, display_alias: nil},
  {name: "SlimeS Add", skill_id: 112, points: 10, display_alias: nil},
  {name: "Poison Coat Add", skill_id: 85, points: 10, display_alias: nil},
  {name: "Paralysis Coat Add", skill_id: 78, points: 10, display_alias: nil},
  {name: "Sleep Coat Add", skill_id: 109, points: 10, display_alias: nil},
  {name: "Power Coat Add", skill_id: 87, points: 10, display_alias: nil},
  {name: "C.Range Coat Add", skill_id: 13, points: 10, display_alias: nil},
  {name: "Exhaust Coat Add", skill_id: 38, points: 10, display_alias: nil},
  {name: "Slime Coat Add", skill_id: 111, points: 10, display_alias: nil},
  {name: "Horn Maestro", skill_id: 72, points: 10, display_alias: nil},
  {name: "Artillery Novice", skill_id: 5, points: 10, display_alias: nil},
  {name: "Artillery Expert", skill_id: 5, points: 15, display_alias: nil},
  {name: "Artillery Master", skill_id: 5, points: 20, display_alias: nil},
  {name: "Bombardier", skill_id: 12, points: 10, display_alias: nil},
  {name: "Recovery Up", skill_id: 99, points: 10, display_alias: nil},
  {name: "Recovery Down", skill_id: 99, points: -10, display_alias: nil},
  {name: "Wide Range +1", skill_id: 143, points: 10, display_alias: nil},
  {name: "Wide Range +2", skill_id: 143, points: 15, display_alias: nil},
  {name: "Item Use Up", skill_id: 70, points: 10, display_alias: nil},
  {name: "Item Use Down", skill_id: 70, points: -10, display_alias: nil},
  {name: "Halve Hunger", skill_id: 65, points: 10, display_alias: nil},
  {name: "Negate Hunger", skill_id: 65, points: 15, display_alias: nil},
  {name: "Raise Hunger", skill_id: 65, points: -10, display_alias: nil},
  {name: "Double Hunger", skill_id: 65, points: -15, display_alias: nil},
  {name: "Gourmand", skill_id: 53, points: 10, display_alias: nil},
  {name: "Scavenger", skill_id: 53, points: 15, display_alias: nil},
  {name: "Speed Eating +1", skill_id: 32, points: 10, display_alias: nil},
  {name: "Speed Eating +2", skill_id: 32, points: 15, display_alias: nil},
  {name: "Slow Eater", skill_id: 32, points: -10, display_alias: nil},
  {name: "Meat Lover", skill_id: 14, points: 10, display_alias: nil},
  {name: "Combination +20%", skill_id: 21, points: 10, display_alias: nil},
  {name: "Combination +45%", skill_id: 21, points: 15, display_alias: nil},
  {name: "Combination -10%", skill_id: 21, points: -10, display_alias: nil},
  {name: "Combination -20%", skill_id: 21, points: -15, display_alias: nil},
  {name: "Combination Pro", skill_id: 20, points: 10, display_alias: nil},
  {name: "Gathering +1", skill_id: 51, points: 10, display_alias: nil},
  {name: "Gathering +2", skill_id: 51, points: 15, display_alias: nil},
  {name: "Gathering Master", skill_id: 51, points: 20, display_alias: nil},
  {name: "Gathering -1", skill_id: 51, points: -10, display_alias: nil},
  {name: "Speed Gatherer", skill_id: 114, points: 10, display_alias: nil},
  {name: "Divine Whim", skill_id: 142, points: 10, display_alias: nil},
  {name: "Spirit's Whim", skill_id: 142, points: 15, display_alias: nil},
  {name: "Spectre's Whim", skill_id: 142, points: -10, display_alias: nil},
  {name: "Devil's Whim", skill_id: 142, points: -15, display_alias: nil},
  {name: "Honey Hunter", skill_id: 64, points: 10, display_alias: nil},
  {name: "Charm Chaser", skill_id: 17, points: 10, display_alias: nil},
  {name: "Charm Hunter", skill_id: 17, points: 15, display_alias: nil},
  {name: "Charm Master", skill_id: 17, points: 20, display_alias: nil},
  {name: "Good Luck", skill_id: 42, points: 10, display_alias: nil},
  {name: "Great Luck", skill_id: 42, points: 15, display_alias: nil},
  {name: "Super Luck", skill_id: 42, points: 20, display_alias: nil},
  {name: "Bad Luck", skill_id: 42, points: -10, display_alias: nil},
  {name: "Horrible Luck", skill_id: 42, points: -15, display_alias: nil},
  {name: "Carving Pro", skill_id: 15, points: 10, display_alias: nil},
  {name: "Carving Expert", skill_id: 15, points: 15, display_alias: nil},
  {name: "Carving Master", skill_id: 15, points: 20, display_alias: nil},
  {name: "Capture Pro", skill_id: 133, points: 10, display_alias: nil},
  {name: "Capture Expert", skill_id: 133, points: 15, display_alias: nil},
  {name: "Capture Master", skill_id: 133, points: 20, display_alias: nil},
  {name: "Capture Guru", skill_id: 81, points: 10, display_alias: nil},
  {name: "Detect", skill_id: 92, points: 10, display_alias: nil},
  {name: "Autotracker", skill_id: 92, points: 15, display_alias: nil},
  {name: "Pro Transporter", skill_id: 134, points: 10, display_alias: nil},
  {name: "Outdoorsman", skill_id: 95, points: 10, display_alias: nil},
  {name: "Anti-Theft", skill_id: 3, points: 10, display_alias: nil},
  {name: "Trap Expert", skill_id: 115, points: 10, display_alias: nil},
  {name: "Flame Aura", skill_id: 48, points: 10, display_alias: nil},
  {name: "Adrenaline +1", skill_id: 86, points: 10, display_alias: nil},
  {name: "Adrenaline +2", skill_id: 86, points: 15, display_alias: nil},
  {name: "Worrywart", skill_id: 86, points: -10, display_alias: nil},
  {name: "Fortify", skill_id: 126, points: 10, display_alias: nil},
  {name: "Latent Power +1", skill_id: 52, points: 10, display_alias: nil},
  {name: "Latent Power +2", skill_id: 52, points: 15, display_alias: nil},
  {name: "Challenger +1", skill_id: 116, points: 10, display_alias: nil},
  {name: "Challenger +2", skill_id: 116, points: 15, display_alias: nil},
  {name: "Peak Performance", skill_id: 138, points: 10, display_alias: nil},
  {name: "Awaken", skill_id: 49, points: 10, display_alias: nil},
  {name: "Guts", skill_id: 57, points: 10, display_alias: nil},
  {name: "Felyne Rally", skill_id: 128, points: 10, display_alias: nil},
  {name: "Felyne Cheer", skill_id: 127, points: 10, display_alias: nil},
  {name: "Auto-Guard", skill_id: 7, points: 10, display_alias: nil},
  {name: "Blightproof", skill_id: 11, points: 10, display_alias: nil},
  {name: "Wellness", skill_id: 122, points: 10, display_alias: nil},
  {name: "Wrath Awoken", skill_id: 50, points: 10, display_alias: nil},
  {name: "Honed Blade", skill_id: 33, points: 10, display_alias: nil},
  {name: "Silver Bullet", skill_id: 123, points: 10, display_alias: nil},
  {name: "Rock Steady", skill_id: 139, points: 10, display_alias: nil},
  {name: "Predatory Focus", skill_id: 107, points: 10, display_alias: nil},
  {name: "Impregnable", skill_id: 47, points: 10, display_alias: nil},
  {name: "Filthy Rich", skill_id: 54, points: 10, display_alias: nil},
  {name: "Infection Resist", skill_id: 68, points: 10, display_alias: nil},
  {name: "Ruthless", skill_id: 89, points: 10, display_alias: nil},
  {name: "Felyne Commander", skill_id: 22, points: 10, display_alias: nil},
  {name: "Riding Pro", skill_id: 101, points: 10, display_alias: nil},
  {name: "Riding Master", skill_id: 101, points: 15, display_alias: nil},
  {name: "Poor Rider", skill_id: 101, points: -10, display_alias: nil},
  {name: "Punishing Skill", skill_id: 73, points: 10, display_alias: nil},
  {name: "Acrobatics", skill_id: 1, points: 10, display_alias: nil},
  {name: "Shields Up", skill_id: 106, points: 10, display_alias: nil},
  {name: "Dancer", skill_id: 44, points: 10, display_alias: nil},
  {name: "Charm Mania", skill_id: 16, points: 10, display_alias: nil},
  {name: "Amplification", skill_id: 2, points: 10, display_alias: nil},
  {name: "Negate Bleeding", skill_id: 10, points: 10, display_alias: nil},
  {name: "Double Bleeding", skill_id: 10, points: -10, display_alias: nil},
  {name: "Full Stomach", skill_id: 29, points: 10, display_alias: nil},
  {name: "Mushroom Lover", skill_id: 74, points: 10, display_alias: nil},
  {name: "Gourmet", skill_id: 4, points: 10, display_alias: nil},
  {name: "Negate Sticky", skill_id: 125, points: 10, display_alias: nil},
  {name: "Range Extend", skill_id: 94, points: 10, display_alias: nil},
  {name: "Behind the Scenes", skill_id: 137, points: 10, display_alias: nil},
  {name: "One with the Blade", skill_id: 9, points: 10, display_alias: nil},
  {name: "Status Criticals", skill_id: 121, points: 10, display_alias: nil},
  {name: "Elemental Criticals", skill_id: 35, points: 10, display_alias: nil},
  {name: "Sticky Fighter", skill_id: 124, points: 10, display_alias: nil},
  {name: "Hidden Power", skill_id: 63, points: 10, display_alias: nil},
  {name: "Trap Master", skill_id: 135, points: 10, display_alias: nil},
  {name: "Hard Hitter", skill_id: 59, points: 10, display_alias: nil},
  {name: "Festive Blessing", skill_id: 88, points: 10, display_alias: nil},
  {name: "Torso Up", skill_id: 132, points: 10, display_alias: nil}
])
DecSkill.create!([
  {skill_id: 40, decoration_id: 1, points: 1},
  {skill_id: 77, decoration_id: 1, points: -1},
  {skill_id: 40, decoration_id: 2, points: 2},
  {skill_id: 77, decoration_id: 3, points: 1},
  {skill_id: 84, decoration_id: 3, points: -1},
  {skill_id: 77, decoration_id: 4, points: 3},
  {skill_id: 84, decoration_id: 4, points: -1},
  {skill_id: 108, decoration_id: 5, points: 1},
  {skill_id: 113, decoration_id: 5, points: -1},
  {skill_id: 108, decoration_id: 6, points: 3},
  {skill_id: 113, decoration_id: 6, points: -1},
  {skill_id: 84, decoration_id: 7, points: 1},
  {skill_id: 40, decoration_id: 7, points: -1},
  {skill_id: 84, decoration_id: 8, points: 3},
  {skill_id: 40, decoration_id: 8, points: -1},
  {skill_id: 27, decoration_id: 9, points: 2},
  {skill_id: 3, decoration_id: 10, points: 2},
  {skill_id: 113, decoration_id: 11, points: 1},
  {skill_id: 108, decoration_id: 11, points: -1},
  {skill_id: 113, decoration_id: 12, points: 2},
  {skill_id: 10, decoration_id: 13, points: 2},
  {skill_id: 125, decoration_id: 14, points: 2},
  {skill_id: 68, decoration_id: 15, points: 1},
  {skill_id: 37, decoration_id: 15, points: -1},
  {skill_id: 68, decoration_id: 16, points: 4},
  {skill_id: 37, decoration_id: 16, points: -2},
  {skill_id: 136, decoration_id: 17, points: 1},
  {skill_id: 108, decoration_id: 17, points: -1},
  {skill_id: 136, decoration_id: 18, points: 2},
  {skill_id: 62, decoration_id: 19, points: 2},
  {skill_id: 19, decoration_id: 20, points: 2},
  {skill_id: 61, decoration_id: 21, points: 1},
  {skill_id: 91, decoration_id: 21, points: -1},
  {skill_id: 61, decoration_id: 22, points: 4},
  {skill_id: 91, decoration_id: 22, points: -2},
  {skill_id: 144, decoration_id: 23, points: 1},
  {skill_id: 42, decoration_id: 23, points: -1},
  {skill_id: 144, decoration_id: 24, points: 3},
  {skill_id: 42, decoration_id: 24, points: -1},
  {skill_id: 6, decoration_id: 25, points: 1},
  {skill_id: 26, decoration_id: 25, points: -1},
  {skill_id: 6, decoration_id: 26, points: 3},
  {skill_id: 26, decoration_id: 26, points: -1},
  {skill_id: 6, decoration_id: 27, points: 5},
  {skill_id: 26, decoration_id: 27, points: -1},
  {skill_id: 39, decoration_id: 28, points: 1},
  {skill_id: 31, decoration_id: 28, points: -1},
  {skill_id: 39, decoration_id: 29, points: 3},
  {skill_id: 31, decoration_id: 29, points: -1},
  {skill_id: 39, decoration_id: 30, points: 5},
  {skill_id: 31, decoration_id: 30, points: -1},
  {skill_id: 120, decoration_id: 31, points: 1},
  {skill_id: 34, decoration_id: 31, points: -1},
  {skill_id: 120, decoration_id: 32, points: 3},
  {skill_id: 34, decoration_id: 32, points: -1},
  {skill_id: 34, decoration_id: 33, points: 1},
  {skill_id: 120, decoration_id: 33, points: -1},
  {skill_id: 34, decoration_id: 34, points: 4},
  {skill_id: 120, decoration_id: 34, points: -2},
  {skill_id: 45, decoration_id: 35, points: 1},
  {skill_id: 140, decoration_id: 35, points: -1},
  {skill_id: 45, decoration_id: 36, points: 3},
  {skill_id: 140, decoration_id: 36, points: -1},
  {skill_id: 140, decoration_id: 37, points: 1},
  {skill_id: 130, decoration_id: 37, points: -1},
  {skill_id: 140, decoration_id: 38, points: 3},
  {skill_id: 130, decoration_id: 38, points: -1},
  {skill_id: 130, decoration_id: 39, points: 1},
  {skill_id: 66, decoration_id: 39, points: -1},
  {skill_id: 130, decoration_id: 40, points: 3},
  {skill_id: 66, decoration_id: 40, points: -1},
  {skill_id: 66, decoration_id: 41, points: 1},
  {skill_id: 45, decoration_id: 41, points: -1},
  {skill_id: 66, decoration_id: 42, points: 3},
  {skill_id: 45, decoration_id: 42, points: -1},
  {skill_id: 30, decoration_id: 43, points: 1},
  {skill_id: 120, decoration_id: 43, points: -1},
  {skill_id: 30, decoration_id: 44, points: 3},
  {skill_id: 120, decoration_id: 44, points: -1},
  {skill_id: 129, decoration_id: 45, points: 1},
  {skill_id: 60, decoration_id: 45, points: -1},
  {skill_id: 129, decoration_id: 46, points: 4},
  {skill_id: 60, decoration_id: 46, points: -2},
  {skill_id: 28, decoration_id: 47, points: 1},
  {skill_id: 39, decoration_id: 47, points: -1},
  {skill_id: 28, decoration_id: 48, points: 4},
  {skill_id: 39, decoration_id: 48, points: -2},
  {skill_id: 35, decoration_id: 49, points: 1},
  {skill_id: 6, decoration_id: 49, points: -1},
  {skill_id: 35, decoration_id: 50, points: 3},
  {skill_id: 6, decoration_id: 50, points: -1},
  {skill_id: 121, decoration_id: 51, points: 1},
  {skill_id: 6, decoration_id: 51, points: -1},
  {skill_id: 121, decoration_id: 52, points: 3},
  {skill_id: 6, decoration_id: 52, points: -1},
  {skill_id: 71, decoration_id: 53, points: 1},
  {skill_id: 100, decoration_id: 53, points: -1},
  {skill_id: 71, decoration_id: 54, points: 2},
  {skill_id: 100, decoration_id: 54, points: -2},
  {skill_id: 71, decoration_id: 55, points: 3},
  {skill_id: 100, decoration_id: 55, points: -2},
  {skill_id: 41, decoration_id: 56, points: 1},
  {skill_id: 23, decoration_id: 56, points: -1},
  {skill_id: 41, decoration_id: 57, points: 4},
  {skill_id: 23, decoration_id: 57, points: -2},
  {skill_id: 52, decoration_id: 58, points: 1},
  {skill_id: 102, decoration_id: 58, points: -1},
  {skill_id: 52, decoration_id: 59, points: 3},
  {skill_id: 102, decoration_id: 59, points: -1},
  {skill_id: 69, decoration_id: 60, points: 1},
  {skill_id: 41, decoration_id: 60, points: -1},
  {skill_id: 69, decoration_id: 61, points: 3},
  {skill_id: 41, decoration_id: 61, points: -1},
  {skill_id: 118, decoration_id: 62, points: 1},
  {skill_id: 117, decoration_id: 62, points: -1},
  {skill_id: 118, decoration_id: 63, points: 3},
  {skill_id: 117, decoration_id: 63, points: -1},
  {skill_id: 86, decoration_id: 64, points: 1},
  {skill_id: 91, decoration_id: 64, points: -1},
  {skill_id: 86, decoration_id: 65, points: 3},
  {skill_id: 91, decoration_id: 65, points: -1},
  {skill_id: 126, decoration_id: 66, points: 1},
  {skill_id: 99, decoration_id: 66, points: -1},
  {skill_id: 126, decoration_id: 67, points: 3},
  {skill_id: 99, decoration_id: 67, points: -1},
  {skill_id: 12, decoration_id: 68, points: 2},
  {skill_id: 72, decoration_id: 69, points: 2},
  {skill_id: 5, decoration_id: 70, points: 2},
  {skill_id: 26, decoration_id: 71, points: 1},
  {skill_id: 6, decoration_id: 71, points: -1},
  {skill_id: 26, decoration_id: 72, points: 3},
  {skill_id: 6, decoration_id: 72, points: -1},
  {skill_id: 26, decoration_id: 73, points: 5},
  {skill_id: 6, decoration_id: 73, points: -1},
  {skill_id: 11, decoration_id: 74, points: 1},
  {skill_id: 60, decoration_id: 74, points: -1},
  {skill_id: 11, decoration_id: 75, points: 4},
  {skill_id: 60, decoration_id: 75, points: -2},
  {skill_id: 46, decoration_id: 76, points: 1},
  {skill_id: 141, decoration_id: 76, points: -1},
  {skill_id: 46, decoration_id: 77, points: 2},
  {skill_id: 141, decoration_id: 78, points: 1},
  {skill_id: 131, decoration_id: 78, points: -1},
  {skill_id: 141, decoration_id: 79, points: 2},
  {skill_id: 131, decoration_id: 80, points: 1},
  {skill_id: 67, decoration_id: 80, points: -1},
  {skill_id: 131, decoration_id: 81, points: 2},
  {skill_id: 67, decoration_id: 82, points: 1},
  {skill_id: 46, decoration_id: 82, points: -1},
  {skill_id: 67, decoration_id: 83, points: 2},
  {skill_id: 31, decoration_id: 84, points: 1},
  {skill_id: 84, decoration_id: 84, points: -1},
  {skill_id: 31, decoration_id: 85, points: 2},
  {skill_id: 91, decoration_id: 86, points: 1},
  {skill_id: 91, decoration_id: 87, points: 2},
  {skill_id: 60, decoration_id: 88, points: 2},
  {skill_id: 97, decoration_id: 89, points: 1},
  {skill_id: 32, decoration_id: 89, points: -1},
  {skill_id: 97, decoration_id: 90, points: 3},
  {skill_id: 32, decoration_id: 90, points: -1},
  {skill_id: 99, decoration_id: 91, points: 1},
  {skill_id: 97, decoration_id: 91, points: -1},
  {skill_id: 99, decoration_id: 92, points: 3},
  {skill_id: 97, decoration_id: 92, points: -1},
  {skill_id: 37, decoration_id: 93, points: 1},
  {skill_id: 60, decoration_id: 93, points: -1},
  {skill_id: 37, decoration_id: 94, points: 3},
  {skill_id: 60, decoration_id: 94, points: -1},
  {skill_id: 36, decoration_id: 95, points: 1},
  {skill_id: 60, decoration_id: 95, points: -1},
  {skill_id: 36, decoration_id: 96, points: 3},
  {skill_id: 60, decoration_id: 96, points: -1},
  {skill_id: 105, decoration_id: 97, points: 1},
  {skill_id: 103, decoration_id: 97, points: -1},
  {skill_id: 105, decoration_id: 98, points: 3},
  {skill_id: 103, decoration_id: 98, points: -1},
  {skill_id: 115, decoration_id: 99, points: 2},
  {skill_id: 32, decoration_id: 100, points: 1},
  {skill_id: 99, decoration_id: 100, points: -1},
  {skill_id: 32, decoration_id: 101, points: 4},
  {skill_id: 99, decoration_id: 101, points: -2},
  {skill_id: 29, decoration_id: 102, points: 2},
  {skill_id: 142, decoration_id: 102, points: -1},
  {skill_id: 117, decoration_id: 103, points: 1},
  {skill_id: 65, decoration_id: 103, points: -1},
  {skill_id: 117, decoration_id: 104, points: 4},
  {skill_id: 65, decoration_id: 104, points: -2},
  {skill_id: 23, decoration_id: 105, points: 1},
  {skill_id: 117, decoration_id: 105, points: -1},
  {skill_id: 23, decoration_id: 106, points: 3},
  {skill_id: 117, decoration_id: 106, points: -1},
  {skill_id: 119, decoration_id: 107, points: 1},
  {skill_id: 37, decoration_id: 107, points: -1},
  {skill_id: 119, decoration_id: 108, points: 3},
  {skill_id: 37, decoration_id: 108, points: -1},
  {skill_id: 65, decoration_id: 109, points: 2},
  {skill_id: 53, decoration_id: 110, points: 2},
  {skill_id: 42, decoration_id: 111, points: 1},
  {skill_id: 142, decoration_id: 111, points: -1},
  {skill_id: 42, decoration_id: 112, points: 4},
  {skill_id: 142, decoration_id: 112, points: -2},
  {skill_id: 133, decoration_id: 113, points: 1},
  {skill_id: 42, decoration_id: 113, points: -1},
  {skill_id: 133, decoration_id: 114, points: 4},
  {skill_id: 42, decoration_id: 114, points: -2},
  {skill_id: 15, decoration_id: 115, points: 1},
  {skill_id: 42, decoration_id: 115, points: -1},
  {skill_id: 15, decoration_id: 116, points: 4},
  {skill_id: 42, decoration_id: 116, points: -2},
  {skill_id: 134, decoration_id: 117, points: 2},
  {skill_id: 51, decoration_id: 118, points: 2},
  {skill_id: 114, decoration_id: 119, points: 2},
  {skill_id: 142, decoration_id: 120, points: 2},
  {skill_id: 143, decoration_id: 121, points: 1},
  {skill_id: 102, decoration_id: 121, points: -1},
  {skill_id: 143, decoration_id: 122, points: 3},
  {skill_id: 102, decoration_id: 122, points: -1},
  {skill_id: 92, decoration_id: 123, points: 2},
  {skill_id: 21, decoration_id: 124, points: 2},
  {skill_id: 20, decoration_id: 125, points: 2},
  {skill_id: 70, decoration_id: 126, points: 2},
  {skill_id: 81, decoration_id: 127, points: 2},
  {skill_id: 95, decoration_id: 128, points: 2},
  {skill_id: 102, decoration_id: 129, points: 2},
  {skill_id: 58, decoration_id: 130, points: 1},
  {skill_id: 104, decoration_id: 130, points: -1},
  {skill_id: 58, decoration_id: 131, points: 2},
  {skill_id: 104, decoration_id: 131, points: -2},
  {skill_id: 58, decoration_id: 132, points: 3},
  {skill_id: 104, decoration_id: 132, points: -2},
  {skill_id: 43, decoration_id: 133, points: 1},
  {skill_id: 58, decoration_id: 133, points: -1},
  {skill_id: 43, decoration_id: 134, points: 4},
  {skill_id: 58, decoration_id: 134, points: -2},
  {skill_id: 104, decoration_id: 135, points: 1},
  {skill_id: 58, decoration_id: 135, points: -1},
  {skill_id: 104, decoration_id: 136, points: 4},
  {skill_id: 58, decoration_id: 136, points: -2},
  {skill_id: 25, decoration_id: 137, points: 1},
  {skill_id: 39, decoration_id: 137, points: -1},
  {skill_id: 25, decoration_id: 138, points: 3},
  {skill_id: 39, decoration_id: 138, points: -1},
  {skill_id: 93, decoration_id: 139, points: 1},
  {skill_id: 104, decoration_id: 139, points: -1},
  {skill_id: 93, decoration_id: 140, points: 4},
  {skill_id: 104, decoration_id: 140, points: -2},
  {skill_id: 55, decoration_id: 141, points: 1},
  {skill_id: 23, decoration_id: 141, points: -1},
  {skill_id: 55, decoration_id: 142, points: 3},
  {skill_id: 23, decoration_id: 142, points: -1},
  {skill_id: 56, decoration_id: 143, points: 1},
  {skill_id: 117, decoration_id: 143, points: -1},
  {skill_id: 56, decoration_id: 144, points: 3},
  {skill_id: 117, decoration_id: 144, points: -1},
  {skill_id: 103, decoration_id: 145, points: 2},
  {skill_id: 76, decoration_id: 146, points: 1},
  {skill_id: 98, decoration_id: 146, points: -1},
  {skill_id: 76, decoration_id: 147, points: 4},
  {skill_id: 98, decoration_id: 147, points: -2},
  {skill_id: 83, decoration_id: 148, points: 1},
  {skill_id: 98, decoration_id: 148, points: -1},
  {skill_id: 83, decoration_id: 149, points: 4},
  {skill_id: 98, decoration_id: 149, points: -2},
  {skill_id: 80, decoration_id: 150, points: 1},
  {skill_id: 98, decoration_id: 150, points: -1},
  {skill_id: 80, decoration_id: 151, points: 4},
  {skill_id: 98, decoration_id: 151, points: -2},
  {skill_id: 75, decoration_id: 152, points: 1},
  {skill_id: 100, decoration_id: 152, points: -1},
  {skill_id: 75, decoration_id: 153, points: 3},
  {skill_id: 100, decoration_id: 153, points: -1},
  {skill_id: 82, decoration_id: 154, points: 2},
  {skill_id: 79, decoration_id: 155, points: 2},
  {skill_id: 24, decoration_id: 156, points: 2},
  {skill_id: 18, decoration_id: 157, points: 1},
  {skill_id: 100, decoration_id: 157, points: -1},
  {skill_id: 110, decoration_id: 158, points: 2},
  {skill_id: 112, decoration_id: 159, points: 2},
  {skill_id: 96, decoration_id: 160, points: 1},
  {skill_id: 100, decoration_id: 160, points: -1},
  {skill_id: 96, decoration_id: 161, points: 4},
  {skill_id: 100, decoration_id: 161, points: -2},
  {skill_id: 100, decoration_id: 162, points: 1},
  {skill_id: 98, decoration_id: 162, points: -1},
  {skill_id: 100, decoration_id: 163, points: 3},
  {skill_id: 98, decoration_id: 163, points: -1},
  {skill_id: 98, decoration_id: 164, points: 1},
  {skill_id: 100, decoration_id: 164, points: -1},
  {skill_id: 98, decoration_id: 165, points: 4},
  {skill_id: 100, decoration_id: 165, points: -2},
  {skill_id: 94, decoration_id: 166, points: 1},
  {skill_id: 71, decoration_id: 166, points: -1},
  {skill_id: 94, decoration_id: 167, points: 3},
  {skill_id: 71, decoration_id: 167, points: -1},
  {skill_id: 90, decoration_id: 168, points: 2},
  {skill_id: 78, decoration_id: 169, points: 1},
  {skill_id: 6, decoration_id: 169, points: -1},
  {skill_id: 78, decoration_id: 170, points: 3},
  {skill_id: 6, decoration_id: 170, points: -1},
  {skill_id: 109, decoration_id: 171, points: 2},
  {skill_id: 85, decoration_id: 172, points: 2},
  {skill_id: 87, decoration_id: 173, points: 1},
  {skill_id: 39, decoration_id: 173, points: -1},
  {skill_id: 87, decoration_id: 174, points: 3},
  {skill_id: 39, decoration_id: 174, points: -1},
  {skill_id: 13, decoration_id: 175, points: 2},
  {skill_id: 111, decoration_id: 176, points: 2},
  {skill_id: 38, decoration_id: 177, points: 2},
  {skill_id: 48, decoration_id: 178, points: 2},
  {skill_id: 49, decoration_id: 179, points: 1},
  {skill_id: 120, decoration_id: 179, points: -1},
  {skill_id: 49, decoration_id: 180, points: 2},
  {skill_id: 120, decoration_id: 180, points: -2},
  {skill_id: 49, decoration_id: 181, points: 3},
  {skill_id: 120, decoration_id: 181, points: -2},
  {skill_id: 57, decoration_id: 182, points: 1},
  {skill_id: 21, decoration_id: 182, points: -1},
  {skill_id: 57, decoration_id: 183, points: 3},
  {skill_id: 21, decoration_id: 183, points: -1},
  {skill_id: 14, decoration_id: 184, points: 1},
  {skill_id: 65, decoration_id: 184, points: -1},
  {skill_id: 14, decoration_id: 185, points: 2},
  {skill_id: 74, decoration_id: 186, points: 2},
  {skill_id: 14, decoration_id: 186, points: -1},
  {skill_id: 64, decoration_id: 187, points: 1},
  {skill_id: 142, decoration_id: 187, points: -1},
  {skill_id: 64, decoration_id: 188, points: 2},
  {skill_id: 8, decoration_id: 189, points: 1},
  {skill_id: 102, decoration_id: 189, points: -1},
  {skill_id: 8, decoration_id: 190, points: 2},
  {skill_id: 116, decoration_id: 191, points: 1},
  {skill_id: 55, decoration_id: 191, points: -1},
  {skill_id: 116, decoration_id: 192, points: 3},
  {skill_id: 55, decoration_id: 192, points: -1},
  {skill_id: 138, decoration_id: 193, points: 1},
  {skill_id: 97, decoration_id: 193, points: -1},
  {skill_id: 138, decoration_id: 194, points: 3},
  {skill_id: 97, decoration_id: 194, points: -1},
  {skill_id: 139, decoration_id: 195, points: 1},
  {skill_id: 26, decoration_id: 195, points: -1},
  {skill_id: 139, decoration_id: 196, points: 4},
  {skill_id: 26, decoration_id: 196, points: -2},
  {skill_id: 128, decoration_id: 197, points: 1},
  {skill_id: 70, decoration_id: 197, points: -1},
  {skill_id: 128, decoration_id: 198, points: 2},
  {skill_id: 127, decoration_id: 199, points: 1},
  {skill_id: 51, decoration_id: 199, points: -1},
  {skill_id: 127, decoration_id: 200, points: 3},
  {skill_id: 51, decoration_id: 200, points: -1},
  {skill_id: 17, decoration_id: 201, points: 1},
  {skill_id: 101, decoration_id: 202, points: 2}
])
Decoration.create!([
  {name: "Steadfast Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Standfast Jewel 1", rarity: 4, slots: 1, avail_online: 5, avail_offline: 3},
  {name: "Paralysis Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Paralysis Jewel 2", rarity: 5, slots: 2, avail_online: 2, avail_offline: 3},
  {name: "Pep Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Pep Jewel 2", rarity: 5, slots: 2, avail_online: 2, avail_offline: 4},
  {name: "Antidote Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Antidote Jewel 2", rarity: 5, slots: 2, avail_online: 3, avail_offline: 5},
  {name: "Def Lock Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Alarm Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Tracker Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 3},
  {name: "Trekker Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Bleed Jewel 1", rarity: 4, slots: 1, avail_online: 5, avail_offline: 9},
  {name: "Sticky Jewel 1", rarity: 7, slots: 1, avail_online: 9, avail_offline: 99},
  {name: "Virus Jewel 1", rarity: 8, slots: 1, avail_online: 11, avail_offline: 99},
  {name: "Virus Jewel 3", rarity: 8, slots: 3, avail_online: 11, avail_offline: 99},
  {name: "Footing Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 3},
  {name: "Tectonic Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Heat Res Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Cold Res Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Earplug Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Earplug Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Wind Res Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Wind Res Jewel 2", rarity: 5, slots: 2, avail_online: 7, avail_offline: 99},
  {name: "Attack Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 2},
  {name: "Attack Jewel 2", rarity: 5, slots: 2, avail_online: 2, avail_offline: 4},
  {name: "Attack Jewel 3", rarity: 6, slots: 3, avail_online: 5, avail_offline: 99},
  {name: "Expert Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Expert Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 5},
  {name: "Expert Jewel 3", rarity: 6, slots: 3, avail_online: 7, avail_offline: 99},
  {name: "Disabler Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Disabler Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Element Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Element Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Blaze Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Blaze Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 99},
  {name: "Stream Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 3},
  {name: "Stream Jewel 2", rarity: 5, slots: 2, avail_online: 4, avail_offline: 7},
  {name: "Bolt Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Bolt Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Frost Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Frost Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Dragon Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 6},
  {name: "Dragon Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Tenderizer Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Tenderizer Jewel 3", rarity: 6, slots: 3, avail_online: 7, avail_offline: 99},
  {name: "Destroyer Jewel 1", rarity: 4, slots: 1, avail_online: 5, avail_offline: 6},
  {name: "Destroyer Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Element Crit Jewel 1", rarity: 8, slots: 1, avail_online: 10, avail_offline: 99},
  {name: "Element Crit Jewel 2", rarity: 8, slots: 2, avail_online: 11, avail_offline: 99},
  {name: "Status Crit Jewel 1", rarity: 8, slots: 1, avail_online: 10, avail_offline: 99},
  {name: "Status Crit Jewel 2", rarity: 8, slots: 2, avail_online: 11, avail_offline: 99},
  {name: "Capacity Jewel 2", rarity: 5, slots: 2, avail_online: 4, avail_offline: 6},
  {name: "Capacity Jewel 3", rarity: 6, slots: 3, avail_online: 7, avail_offline: 99},
  {name: "Capacity+ Jewel 3", rarity: 8, slots: 3, avail_online: 10, avail_offline: 99},
  {name: "Charger Jewel 1", rarity: 4, slots: 1, avail_online: 5, avail_offline: 4},
  {name: "Charger Jewel 3", rarity: 6, slots: 3, avail_online: 7, avail_offline: 99},
  {name: "Throttle Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Throttle Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 99},
  {name: "KO Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "KO Jewel 2", rarity: 5, slots: 2, avail_online: 4, avail_offline: 7},
  {name: "Drain Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Drain Jewel 2", rarity: 5, slots: 2, avail_online: 8, avail_offline: 99},
  {name: "Potential Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 6},
  {name: "Potential Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Fortitude Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Fortitude Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Bombardier Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 6},
  {name: "Sonorous Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Artillery Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Defense Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 3},
  {name: "Defense Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 5},
  {name: "Defense Jewel 3", rarity: 7, slots: 3, avail_online: 9, avail_offline: 99},
  {name: "Resistor Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Resistor Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Fire Res Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Nul-Fire Jewel", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Water Res Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Nul-Water Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Thunder Res Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Nul-Thunder Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Ice Res Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Nul-Ice Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Dragon Res Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Nul-Dragon Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Protection Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Asylum Jewel 1", rarity: 4, slots: 1, avail_online: 7, avail_offline: 99},
  {name: "Vitality Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Rec Speed Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Rec Speed Jewel 2", rarity: 5, slots: 2, avail_online: 2, avail_offline: 4},
  {name: "Medicine Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Medicine Jewel 2", rarity: 5, slots: 2, avail_online: 4, avail_offline: 7},
  {name: "Evasion Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Evasion Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Jumping Jewel 1", rarity: 4, slots: 1, avail_online: 5, avail_offline: 5},
  {name: "Jumping Jewel 2", rarity: 8, slots: 2, avail_online: 10, avail_offline: 99},
  {name: "Sheath Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Sheath Jewel 2", rarity: 4, slots: 2, avail_online: 5, avail_offline: 99},
  {name: "Trapmaster Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Gobbler Jewel 1", rarity: 4, slots: 1, avail_online: 5, avail_offline: 5},
  {name: "Gobbler Jewel 3", rarity: 6, slots: 3, avail_online: 7, avail_offline: 9},
  {name: "Satisfaction Jewel 1", rarity: 7, slots: 1, avail_online: 9, avail_offline: 99},
  {name: "Sprinter Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 3},
  {name: "Sprinter Jewel 3", rarity: 6, slots: 3, avail_online: 6, avail_offline: 9},
  {name: "Physique Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Physique Jewel 2", rarity: 5, slots: 2, avail_online: 6, avail_offline: 9},
  {name: "Refresh Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Refresh Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Hungerless Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Metabolism Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 3},
  {name: "Fate Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Fate Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Capture Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Capture Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Carver Jewel 1", rarity: 4, slots: 1, avail_online: 7, avail_offline: 9},
  {name: "Carver Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Transporter Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 3},
  {name: "Gathering Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 4},
  {name: "Spree Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 4},
  {name: "Blessing Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Friendship Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Friendship Jewel 2", rarity: 5, slots: 2, avail_online: 4, avail_offline: 7},
  {name: "Psychic Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 3},
  {name: "Professor Jewel", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Factory Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Enduring Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Perception Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Ranger Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Ninja Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Handicraft Jewel 2", rarity: 5, slots: 2, avail_online: 6, avail_offline: 99},
  {name: "Handicraft Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Handicraft+ Jewel 3", rarity: 8, slots: 3, avail_online: 10, avail_offline: 99},
  {name: "Fencer Jewel 1", rarity: 4, slots: 1, avail_online: 7, avail_offline: 10},
  {name: "Fencer Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Razor Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Razor Jewel 3", rarity: 6, slots: 3, avail_online: 5, avail_offline: 99},
  {name: "Draw Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 6},
  {name: "Draw Jewel 2", rarity: 5, slots: 2, avail_online: 6, avail_offline: 99},
  {name: "Gambit Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 5},
  {name: "Gambit Jewel 3", rarity: 6, slots: 3, avail_online: 6, avail_offline: 9},
  {name: "Ironwall Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 4},
  {name: "Ironwall Jewel 2", rarity: 5, slots: 2, avail_online: 6, avail_offline: 99},
  {name: "Shield Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Shield Jewel 2", rarity: 5, slots: 2, avail_online: 6, avail_offline: 9},
  {name: "Grinder Jewel", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Forceshot Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Forceshot Jewel 3", rarity: 6, slots: 3, avail_online: 5, avail_offline: 99},
  {name: "Pierce Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Pierce Jewel 3", rarity: 6, slots: 3, avail_online: 6, avail_offline: 9},
  {name: "Pellet Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Pellet Jewel 3", rarity: 6, slots: 3, avail_online: 6, avail_offline: 9},
  {name: "ShotPlus Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 3},
  {name: "ShotPlus Jewel 2", rarity: 5, slots: 2, avail_online: 3, avail_offline: 5},
  {name: "PiercePlus Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "PelletPlus Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 5},
  {name: "CragPlus Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "ClustPlus Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 5},
  {name: "SlicePlus Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "SlimePlus Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Salvo Jewel 1", rarity: 4, slots: 1, avail_online: 3, avail_offline: 5},
  {name: "Salvo Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Quickload Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Quickload Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 5},
  {name: "Absorber Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 4},
  {name: "Absorber Jewel 3", rarity: 6, slots: 3, avail_online: 6, avail_offline: 9},
  {name: "Range Jewel 1", rarity: 9, slots: 1, avail_online: 12, avail_offline: 99},
  {name: "Range Jewel 2", rarity: 9, slots: 2, avail_online: 12, avail_offline: 99},
  {name: "Sniper Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Paracoat Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Paracoat Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Sleepcoat Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Poisoncoat Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Powercoat Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 3},
  {name: "Powercoat Jewel 2", rarity: 5, slots: 2, avail_online: 4, avail_offline: 7},
  {name: "Rangecoat Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 3},
  {name: "Slimecoat Jewel 1", rarity: 4, slots: 1, avail_online: 6, avail_offline: 9},
  {name: "Draincoat Jewel 1", rarity: 4, slots: 1, avail_online: 2, avail_offline: 4},
  {name: "Torchlight Jewel 1", rarity: 4, slots: 1, avail_online: 6, avail_offline: 99},
  {name: "Release Jewel 2", rarity: 5, slots: 2, avail_online: 8, avail_offline: 99},
  {name: "Catalyst Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Catalyst+ Jewel 3", rarity: 8, slots: 3, avail_online: 10, avail_offline: 99},
  {name: "Guts Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Guts Jewel 2", rarity: 5, slots: 2, avail_online: 8, avail_offline: 99},
  {name: "Meateater Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Meatlover Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Mushroom Jewel 1", rarity: 7, slots: 1, avail_online: 9, avail_offline: 99},
  {name: "Honeybee Jewel 1", rarity: 4, slots: 1, avail_online: 99, avail_offline: 3},
  {name: "Queenbee Jewel 1", rarity: 4, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Biology Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Microbio Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Spirit Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Spirit Jewel 2", rarity: 5, slots: 2, avail_online: 8, avail_offline: 99},
  {name: "Flawless Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Flawless Jewel 2", rarity: 5, slots: 2, avail_online: 8, avail_offline: 99},
  {name: "Steady Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Steady Jewel 3", rarity: 6, slots: 3, avail_online: 8, avail_offline: 99},
  {name: "Player Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 2},
  {name: "Morale Jewel 1", rarity: 5, slots: 1, avail_online: 4, avail_offline: 7},
  {name: "Leader Jewel 1", rarity: 4, slots: 1, avail_online: 1, avail_offline: 1},
  {name: "Leader Jewel 2", rarity: 5, slots: 2, avail_online: 5, avail_offline: 8},
  {name: "Charmer Jewel 1", rarity: 4, slots: 1, avail_online: 8, avail_offline: 99},
  {name: "Rider Jewel 1", rarity: 7, slots: 1, avail_online: 9, avail_offline: 99}
])
Skill.create!([
  {name: "Acrobat", alias_id: nil},
  {name: "Amplifier", alias_id: nil},
  {name: "Anti-Theft", alias_id: nil},
  {name: "Appetite", alias_id: nil},
  {name: "Artillery", alias_id: nil},
  {name: "Attack", alias_id: nil},
  {name: "Auto-Guard", alias_id: nil},
  {name: "Biology", alias_id: nil},
  {name: "Blade", alias_id: nil},
  {name: "Bleed Res", alias_id: nil},
  {name: "Blight Res", alias_id: nil},
  {name: "Bomb Boost", alias_id: nil},
  {name: "C.Range C+", alias_id: nil},
  {name: "Carnivore", alias_id: nil},
  {name: "Carving", alias_id: nil},
  {name: "Charm Collector", alias_id: nil},
  {name: "Charmer", alias_id: nil},
  {name: "Clust S+", alias_id: nil},
  {name: "Cold Res", alias_id: nil},
  {name: "Combo Plus", alias_id: nil},
  {name: "Combo Rate", alias_id: nil},
  {name: "Commander", alias_id: nil},
  {name: "Constitution", alias_id: nil},
  {name: "Crag S+", alias_id: nil},
  {name: "Critical Draw", alias_id: nil},
  {name: "Defense", alias_id: nil},
  {name: "Defense Lock", alias_id: nil},
  {name: "Destroyer", alias_id: nil},
  {name: "Diet", alias_id: nil},
  {name: "Dragon Attack", alias_id: nil},
  {name: "Dragon Res", alias_id: nil},
  {name: "Eating", alias_id: nil},
  {name: "Edgemaster", alias_id: nil},
  {name: "Elemental Attack", alias_id: nil},
  {name: "Elemental Crit", alias_id: nil},
  {name: "Evade Distance", alias_id: nil},
  {name: "Evasion", alias_id: nil},
  {name: "Exhaust C+", alias_id: nil},
  {name: "Expert", alias_id: nil},
  {name: "Faint", alias_id: nil},
  {name: "Fast Charge", alias_id: nil},
  {name: "Fate", alias_id: nil},
  {name: "Fencing", alias_id: nil},
  {name: "Finesse", alias_id: nil},
  {name: "Fire Attack", alias_id: nil},
  {name: "Fire Res", alias_id: nil},
  {name: "Firm Defence", alias_id: nil},
  {name: "Flame Aura", alias_id: nil},
  {name: "Free Element", alias_id: nil},
  {name: "Fury", alias_id: nil},
  {name: "Gathering", alias_id: nil},
  {name: "Gloves Off", alias_id: nil},
  {name: "Gluttony", alias_id: nil},
  {name: "Greedy", alias_id: nil},
  {name: "Guard", alias_id: nil},
  {name: "Guard Up", alias_id: nil},
  {name: "Guts", alias_id: nil},
  {name: "Handicraft", alias_id: nil},
  {name: "Hard Hitting", alias_id: nil},
  {name: "Health", alias_id: nil},
  {name: "Hearing", alias_id: nil},
  {name: "Heat Res", alias_id: nil},
  {name: "Hidden Power", alias_id: nil},
  {name: "Honey", alias_id: nil},
  {name: "Hunger", alias_id: nil},
  {name: "Ice Attack", alias_id: nil},
  {name: "Ice Res", alias_id: nil},
  {name: "Infection Res", alias_id: nil},
  {name: "KO", alias_id: nil},
  {name: "Lasting Power", alias_id: nil},
  {name: "Loading", alias_id: nil},
  {name: "Maestro", alias_id: nil},
  {name: "Martial Arts", alias_id: nil},
  {name: "Mushrooms", alias_id: nil},
  {name: "Normal S+", alias_id: nil},
  {name: "Normal Up", alias_id: nil},
  {name: "Paralysis", alias_id: nil},
  {name: "Paralysis C+", alias_id: nil},
  {name: "Pellet S+", alias_id: nil},
  {name: "Pellet Up", alias_id: nil},
  {name: "Perception", alias_id: nil},
  {name: "Pierce S+", alias_id: nil},
  {name: "Pierce Up", alias_id: nil},
  {name: "Poison", alias_id: nil},
  {name: "Poison C+", alias_id: nil},
  {name: "Potential", alias_id: nil},
  {name: "Power C+", alias_id: nil},
  {name: "Prayer", alias_id: nil},
  {name: "Precise Attack", alias_id: nil},
  {name: "Precision", alias_id: nil},
  {name: "Protection", alias_id: nil},
  {name: "Psychic", alias_id: nil},
  {name: "Punishing Draw", alias_id: nil},
  {name: "Range Extend", alias_id: nil},
  {name: "Ranger", alias_id: nil},
  {name: "Rapid Fire", alias_id: nil},
  {name: "Rec Speed", alias_id: nil},
  {name: "Recoil", alias_id: nil},
  {name: "Recovery Level", alias_id: nil},
  {name: "Reload Speed", alias_id: nil},
  {name: "Rider", alias_id: nil},
  {name: "Sense", alias_id: nil},
  {name: "Sharpening Speed", alias_id: nil},
  {name: "Sharpness", alias_id: nil},
  {name: "Sheathing", alias_id: nil},
  {name: "Shielder", alias_id: nil},
  {name: "Single-Minded", alias_id: nil},
  {name: "Sleep", alias_id: nil},
  {name: "Sleep C+", alias_id: nil},
  {name: "Slicing S+", alias_id: nil},
  {name: "Slime C+", alias_id: nil},
  {name: "Slime S+", alias_id: nil},
  {name: "Snow/Mud Res", alias_id: nil},
  {name: "Speed Gather", alias_id: nil},
  {name: "Speed Setup", alias_id: nil},
  {name: "Spirit", alias_id: nil},
  {name: "Stamina", alias_id: nil},
  {name: "Stamina Drain", alias_id: nil},
  {name: "Stamina Recovery", alias_id: nil},
  {name: "Status", alias_id: nil},
  {name: "Status Crit", alias_id: nil},
  {name: "Status Res", alias_id: nil},
  {name: "Steadyhand", alias_id: nil},
  {name: "Sticky Fighter", alias_id: nil},
  {name: "Sticky Res", alias_id: nil},
  {name: "Survivor", alias_id: nil},
  {name: "Team Leader", alias_id: nil},
  {name: "Team Player", alias_id: nil},
  {name: "Tenderizer", alias_id: nil},
  {name: "Thunder Attack", alias_id: nil},
  {name: "Thunder Res", alias_id: nil},
  {name: "Torso Up", alias_id: nil},
  {name: "Tranquilizer", alias_id: nil},
  {name: "Transporter", alias_id: nil},
  {name: "Trap Master", alias_id: nil},
  {name: "Tremor Res", alias_id: nil},
  {name: "Tricksy", alias_id: nil},
  {name: "Unscathed", alias_id: nil},
  {name: "Unshakable", alias_id: nil},
  {name: "Water Attack", alias_id: nil},
  {name: "Water Res", alias_id: nil},
  {name: "Whim", alias_id: nil},
  {name: "Wide Range", alias_id: nil},
  {name: "Wind Res", alias_id: nil}
])
